#!/bin/bash

TEMPLATES_DIR="$DOTFILES/Helpers/mp/templates"
while getopts "e:h" opt; do
    case $opt in
    e)
        nvim "$TEMPLATES_DIR/$OPTARG"
        exit 0
        ;;
    h)
        echo "p [arg]: create a directory using one of the templates in $TEMPLATES_DIR"
        echo "p -e [arg]: edit the template"
        exit 0
        ;;
    \?)
        echo "invalid option: -$OPTARG"
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

PROJECT_NAME=$1

if [ -z "$PROJECT_NAME" ]; then
	echo "Usage: $0 <template-name>"
	echo "Available templates:"
	ls "$TEMPLATES_DIR"
	exit 1
fi

TEMPLATE="$TEMPLATES_DIR/$PROJECT_NAME"

if [ ! -d "$TEMPLATE" ]; then
	echo "Error: Template '$PROJECT_NAME' not found in $TEMPLATES_DIR"
	echo "Available templates:"
	ls "$TEMPLATES_DIR"
	exit 1
fi

# Use current directory name or prompt for project name
DEST=${2:-$(basename "$PWD")}

if [ -d "$DEST" ]; then
	echo "Error: Directory '$DEST' already exists."
	exit 1
fi

cp -r "$TEMPLATE" "$DEST"
rm -rf "$DEST/.git"

DEST_PATH="$(pwd)/$DEST"

git -C "$DEST_PATH" init
git -C "$DEST_PATH" add .
git -C "$DEST_PATH" commit -m "Initial commit"

cd "$DEST_PATH"
nvim .
