eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(fnm env --shell zsh)" 
fpath=("$HOME/Helpers/completions" $fpath)
autoload -Uz compinit
compinit

# Setting PATH for Python 3.14
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.14/bin:${PATH}"
export PATH

eval "$(fnm env --shell zsh)"
